name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Install TensorFlow
      run: |
        mkdir ~/tensorflow
        cd ~/tensorflow
        wget https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-$TENSORFLOW_VERSION.tar.gz
        tar xvfz libtensorflow-cpu-linux-x86_64-$TENSORFLOW_VERSION.tar.gz
        ls
      env:
        TENSORFLOW_VERSION: 2.3.0
    - run: |
        export LD_LIBRARY_PATH=$HOME/tensorflow/lib:$LD_LIBRARY_PATH
        bundle exec rake test
